### ISSUE TITLE
yam correlate 1

### ISSUE THREAD

**Issue by shubham-geolearner** [trichter/yam#17]
when I run this 'yam correlate 1'. It consumes all the memory and in the end system crashes. I am doing this for 74 mseed files. My system has 32 GB memory with 64 GB swap memory

**Comment by trichter** [comment]
Hi! What is your setup and configuration? Do you have 74 stations?

**Comment by shubham-geolearner** [comment]
Hi..I'm following this link
https://nbviewer.org/github/trichter/notebooks/blob/master/yam_velocity_variations_patcx/processing_patcx.ipynb
to calculate seismic velocity variation at a station. I have 74 days data (mseed files).

**Comment by trichter** [comment]
Sorry, I am still not clear. Do you follow the tutorial 1 to 1 or do you use your own data?

**Comment by shubham-geolearner** [comment]
I am using my own station data. 
Yes with the example data things are working fine at my end but when I am using own data it throws the problem. 
I am using the mint OS (linux).

**Comment by trichter** [comment]
It is difficult to get to the root of the problem without more information. Can you post the log output and configuration? What is the sampling rate of your data? How large are your data files? Which versions of ObsPy and yam are you using? Please also post output of `obspy-print your_data_file`.

**Comment by alemkhodadadi** [comment]
I have the same issue with my own data. 
`yam info` gives me the following: 
```
Stations:
    AN.EE AN.SS AN.TT
    3 stations, 9 channels
Raw data (expression for day files):
    day_files/{network}.{station}.{location}.{channel}*.mseed
    90 files found
Config ids:
    c Corr: 1
    s Stack: None
    t Stretch: None
Correlations (channel combinations, correlations calculated):
    None
Stacks:
    None
Stretching matrices:
    None
```
but when I run `yam correlate 1 --parallel-inner-loop -n 3`, It stuck at 0 percent and then the computer will crash. I'm using Linux. 

obspy-print shows the stats as below:

```
network: OT
         station: EV03
        location: 
         channel: DPE
       starttime: 2018-08-03T00:47:22.987500Z
         endtime: 2018-08-03T00:57:22.987500Z
   sampling_rate: 400.0
           delta: 0.0025
            npts: 240001
           calib: 1.0
         _format: MSEED
           mseed: AttribDict({'dataquality': 'D', 'number_of_records': 476, 'encoding': 'FLOAT64', 'byteorder': '<', 'record_length': 4096, 'filesize': 1949696}
```
